drop database agt;
create database agt;
use agt;

CREATE TABLE municipios (
    id_municipio INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    estado CHAR(2) NOT NULL
);

CREATE TABLE logins (
    id_login INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    nivel_acesso ENUM('Admin', 'User') NOT NULL
);

CREATE TABLE aliquotas (
    id_aliquota INT AUTO_INCREMENT PRIMARY KEY,
    id_municipio INT NOT NULL,
    cod_servico DECIMAL(10,2) NOT NULL,
    desc_servico TEXT NOT NULL,
    aliquota_iss DECIMAL(5,2) NOT NULL,
    lei_vigente VARCHAR(255),
    FOREIGN KEY (id_municipio) REFERENCES municipios(id_municipio)
);

CREATE TABLE unidades (
    id_unidade INT AUTO_INCREMENT PRIMARY KEY,
    cod_entidade VARCHAR(50) NOT NULL,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    nome_fantasia VARCHAR(255),
    endereco TEXT,
    id_municipio INT NOT NULL,
    cep VARCHAR(15),
    FOREIGN KEY (id_municipio) REFERENCES municipios(id_municipio)
);

CREATE TABLE cadastro (
    id_cadastro INT AUTO_INCREMENT PRIMARY KEY,
    id_unidade INT NOT NULL,
    id_municipio INT NOT NULL,
    cnpj_cadastro VARCHAR(20),
    sistema VARCHAR(255),
    site VARCHAR(2048),
    login_sistema VARCHAR(255),
    senha_sistema VARCHAR(255),
    dia_vencimento INT CHECK (dia_vencimento BETWEEN 1 AND 31),
    observacao VARCHAR(2048),
    FOREIGN KEY (id_unidade) REFERENCES unidades(id_unidade),
    FOREIGN KEY (id_municipio) REFERENCES municipios(id_municipio)
);

CREATE TABLE contador_relatorios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    quantidade INT NOT NULL
);

INSERT INTO contador_relatorios (id, quantidade) VALUES (1, 0);

ALTER TABLE cadastro
DROP FOREIGN KEY cadastro_ibfk_1; -- Nome padrão, pode variar. Verifique seu DDL.

ALTER TABLE cadastro
ADD CONSTRAINT fk_unidade
FOREIGN KEY (id_unidade) REFERENCES unidades(id_unidade) ON DELETE CASCADE;


INSERT INTO municipios (nome, estado) VALUES
('Nenhum', 'NA'), -- Para o caso de "Nenhuma alíquota selecionada"
('Curitiba', 'PR'),
('Pinhais', 'PR'),
('Londrina', 'PR'),
('Maringá', 'PR'),
('Ponta Grossa', 'PR'),
('São José dos Pinhais', 'PR'),
('Cascavel', 'PR'),
('Foz do Iguaçu', 'PR'),
('Colombo', 'PR'),
('Guarapuava', 'PR'),
('Araucária', 'PR'),
('São Paulo', 'SP'),
('Rio de Janeiro', 'RJ'),
('Belo Horizonte', 'MG'),
('Porto Alegre', 'RS'),
('Salvador', 'BA'),
('Fortaleza', 'CE'),
('Recife', 'PE'),
('Manaus', 'AM'),
('Goiânia', 'GO');


INSERT INTO aliquotas (id_municipio, cod_servico, desc_servico, aliquota_iss, lei_vigente) VALUES
((SELECT id_municipio FROM municipios WHERE nome = 'Nenhum'), '0.00','Nenhuma alíquota selecionada.','0', NULL),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'3.05', 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário. ', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'7.02', 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes, inclusive (exceto - sondagem, perfuração de poços, escavação, drenagem e irrigação, terraplanagem, pavimentação.', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'7.04', 'Demolição. ', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'7.05', 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres (exceto o fornecimento de mercadorias produzidas pelo prestador dos serviços, fora do local da prestação dos serviços, que fica sujeito ao ICMS) ', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'7.09', 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer. ', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'7.10', 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres', '2.50', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'7.11', 'Decoração E Jardinagem, Inclusive Corte E Poda De Árvores', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'7.12', 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'7.16', 'Florestamento, reflorestamento,  semeadura, adubação e congêneres', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'7.17', 'Escoramento, contenção de encostas e serviços congêneres', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'7.18', '- Limpeza E Dragagem De Rios, Portos, Canais, Baías, Lagos, Lagoas, Represas, Açudes E Congêneres e ', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'7.19', 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'11.0', 'Vigilância, segurança ou monitoramento de bens e pessoas', '2.50', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'16.02', 'Outros serviços de transporte de natureza municipal. (Incluído pela Lei Complementar nº 157, de 2016)', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'17.05', 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'),'17.10', 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.', '5', 'Lei Complementar nº 40/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'3.05', 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'7.02', 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'7.04', 'Demolição.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'7.05', 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'7.09', 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'7.10', 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.', '2.50', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'7.11', 'Decoração e jardinagem, inclusive corte e poda de árvores.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'7.12', 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'7.16', 'Florestamento, reflorestamento, semeadura, adubação e congêneres.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'7.17', 'Escoramento, contenção de encostas e serviços congêneres.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'7.18', 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'7.19', 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'11.0', 'Vigilância, segurança ou monitoramento de bens e pessoas.', '2.50', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'16.02', 'Outros serviços de transporte de natureza municipal. (Incluído pela Lei Complementar nº 157, de 2016)', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'17.05', 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Pinhais'),'17.10', 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.', '5', 'Lei nº 501/2001, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'3.05', 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'7.02', 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'7.04', 'Demolição.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'7.05', 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'7.09', 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'7.10', 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.', '2.50', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'7.11', 'Decoração e jardinagem, inclusive corte e poda de árvores.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'7.12', 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'7.16', 'Florestamento, reflorestamento, semeadura, adubação e congêneres.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'7.17', 'Escoramento, contenção de encostas e serviços congêneres.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'7.18', 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'7.19', 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'11.0', 'Vigilância, segurança ou monitoramento de bens e pessoas.', '2.50', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'16.02', 'Outros serviços de transporte de natureza municipal.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'17.05', 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Londrina'),'17.10', 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.', '5', 'Lei Complementar nº 416/2011, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'3.05', 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'7.02', 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'7.04', 'Demolição.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'7.05', 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'7.09', 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'7.10', 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.', '2.50', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'7.11', 'Decoração e jardinagem, inclusive corte e poda de árvores.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'7.12', 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'7.16', 'Florestamento, reflorestamento, semeadura, adubação e congêneres.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'7.17', 'Escoramento, contenção de encostas e serviços congêneres.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'7.18', 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'7.19', 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'11.0', 'Vigilância, segurança ou monitoramento de bens e pessoas.', '2.50', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'16.02', 'Outros serviços de transporte de natureza municipal.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'17.05', 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Maringá'),'17.10', 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.', '5', 'Lei Complementar nº 632/2006, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'3.05', 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'7.02', 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'7.04', 'Demolição.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'7.05', 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'7.09', 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'7.10', 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.', '2.50', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'7.11', 'Decoração e jardinagem, inclusive corte e poda de árvores.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'7.12', 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'7.16', 'Florestamento, reflorestamento, semeadura, adubação e congêneres.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'7.17', 'Escoramento, contenção de encostas e serviços congêneres.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'7.18', 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'7.19', 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'11.0', 'Vigilância, segurança ou monitoramento de bens e pessoas.', '2.50', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'16.02', 'Outros serviços de transporte de natureza municipal.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'17.05', 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Ponta Grossa'),'17.10', 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.', '5', 'Lei Complementar nº 222/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'3.05', 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'7.02', 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'7.04', 'Demolição.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'7.05', 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'7.09', 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'7.10', 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.', '2.50', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'7.11', 'Decoração e jardinagem, inclusive corte e poda de árvores.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'7.12', 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'7.16', 'Florestamento, reflorestamento, semeadura, adubação e congêneres.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'7.17', 'Escoramento, contenção de encostas e serviços congêneres.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'7.18', 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'7.19', 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'11.0', 'Vigilância, segurança ou monitoramento de bens e pessoas.', '2.50', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'16.02', 'Outros serviços de transporte de natureza municipal.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'17.05', 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'São José dos Pinhais'),'17.10', 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'3.05', 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'7.02', 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'7.04', 'Demolição.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'7.05', 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'7.09', 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'7.10', 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.', '2.50', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'7.11', 'Decoração e jardinagem, inclusive corte e poda de árvores.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'7.12', 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'7.16', 'Florestamento, reflorestamento, semeadura, adubação e congêneres.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'7.17', 'Escoramento, contenção de encostas e serviços congêneres.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'7.18', 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'7.19', 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'11.0', 'Vigilância, segurança ou monitoramento de bens e pessoas.', '2.50', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'16.02', 'Outros serviços de transporte de natureza municipal.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'17.05', 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Cascavel'),'17.10', 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.', '5', 'Lei Complementar nº 3.448/2007, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'3.05', 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'7.02', 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'7.04', 'Demolição.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'7.05', 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'7.09', 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'7.10', 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.', '2.50', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'7.11', 'Decoração e jardinagem, inclusive corte e poda de árvores.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'7.12', 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'7.16', 'Florestamento, reflorestamento, semeadura, adubação e congêneres.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'7.17', 'Escoramento, contenção de encostas e serviços congêneres.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'7.18', 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'7.19', 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'11.0', 'Vigilância, segurança ou monitoramento de bens e pessoas.', '2.50', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'16.02', 'Outros serviços de transporte de natureza municipal.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'17.05', 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Foz do Iguaçu'),'17.10', 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.', '5', 'Lei Complementar nº 82/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'3.05', 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'7.02', 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'7.04', 'Demolição.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'7.05', 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'7.09', 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'7.10', 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.', '2.50', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'7.11', 'Decoração e jardinagem, inclusive corte e poda de árvores.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'7.12', 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'7.16', 'Florestamento, reflorestamento, semeadura, adubação e congêneres.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'7.17', 'Escoramento, contenção de encostas e serviços congêneres.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'7.18', 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'7.19', 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'11.0', 'Vigilância, segurança ou monitoramento de bens e pessoas.', '2.50', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'16.02', 'Outros serviços de transporte de natureza municipal.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'17.05', 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Colombo'),'17.10', 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.', '5', 'Lei Complementar nº 17/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'3.05', 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'7.02', 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'7.04', 'Demolição.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'7.05', 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'7.09', 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'7.10', 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.', '2.50', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'7.11', 'Decoração e jardinagem, inclusive corte e poda de árvores.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'7.12', 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'7.16', 'Florestamento, reflorestamento, semeadura, adubação e congêneres.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'7.17', 'Escoramento, contenção de encostas e serviços congêneres.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'7.18', 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'7.19', 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'11.0', 'Vigilância, segurança ou monitoramento de bens e pessoas.', '2.50', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'16.02', 'Outros serviços de transporte de natureza municipal.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'17.05', 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Guarapuava'),'17.10', 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.', '5', 'Lei Complementar nº 052/2003, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'3.05', 'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'7.02', 'Execução, por administração, empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'7.04', 'Demolição.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'7.05', 'Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'7.09', 'Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'7.10', 'Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres.', '2.50', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'7.11', 'Decoração e jardinagem, inclusive corte e poda de árvores.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'7.12', 'Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'7.16', 'Florestamento, reflorestamento, semeadura, adubação e congêneres.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'7.17', 'Escoramento, contenção de encostas e serviços congêneres.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'7.18', 'Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'7.19', 'Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'11.0', 'Vigilância, segurança ou monitoramento de bens e pessoas.', '2.50', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'16.02', 'Outros serviços de transporte de natureza municipal.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'17.05', 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II'),
((SELECT id_municipio FROM municipios WHERE nome = 'Araucária'),'17.10', 'Planejamento, organização e administração de feiras, exposições, congressos e congêneres.', '5', 'Lei Complementar nº 01/2004, art. 8º-A, II');

-- Inserir dados na tabela unidades
INSERT INTO unidades (cod_entidade, cnpj, nome_fantasia, endereco, id_municipio, cep)
VALUES
('SESI', '12.345.678/0001-90', 'Unidade A', 'Rua das Flores, 123', (SELECT id_municipio FROM municipios WHERE nome = 'São Paulo'), '01234-567'),
('SENAI', '98.765.432/0001-01', 'Unidade B', 'Avenida Paulista, 987', (SELECT id_municipio FROM municipios WHERE nome = 'São Paulo'), '01310-000'),
('FIEP', '21.987.654/0001-02', 'Unidade C', 'Rua Rio de Janeiro, 456', (SELECT id_municipio FROM municipios WHERE nome = 'Rio de Janeiro'), '20000-000'),
('IEL', '34.567.890/0001-03', 'Unidade D', 'Rua Bahia, 789', (SELECT id_municipio FROM municipios WHERE nome = 'Salvador'), '40000-000'),
('MATRIZ', '45.678.901/0001-04', 'Unidade E', 'Avenida Brasil, 234', (SELECT id_municipio FROM municipios WHERE nome = 'Belo Horizonte'), '30100-000'),
('ENT006', '56.789.012/0001-05', 'Unidade F', 'Rua dos Andradas, 555', (SELECT id_municipio FROM municipios WHERE nome = 'Porto Alegre'), '90000-000'),
('ENT007', '67.890.123/0001-06', 'Unidade G', 'Rua Paraná, 321', (SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'), '80000-000'),
('ENT008', '78.901.234/0001-07', 'Unidade H', 'Rua Amazonas, 1234', (SELECT id_municipio FROM municipios WHERE nome = 'Recife'), '50000-000'),
('ENT009', '89.012.345/0001-08', 'Unidade I', 'Avenida Rio Branco, 432', (SELECT id_municipio FROM municipios WHERE nome = 'Fortaleza'), '60000-000'),
('ENT010', '90.123.456/0001-09', 'Unidade J', 'Rua Sergipe, 765', (SELECT id_municipio FROM municipios WHERE nome = 'Manaus'), '69000-000');


INSERT INTO cadastro (id_cadastro, id_unidade, id_municipio, cnpj_cadastro, sistema, site, login_sistema, senha_sistema, dia_vencimento, observacao) VALUES
(1, (SELECT id_unidade FROM unidades WHERE cnpj = '12.345.678/0001-90'), (SELECT id_municipio FROM municipios WHERE nome = 'São Paulo'), '12.345.678/0001-99', 'Sistema A', 'www.google.com', 'usuario1', 'senha123', 3, 'Primeiro registro'),
(2, (SELECT id_unidade FROM unidades WHERE cnpj = '98.765.432/0001-01'), (SELECT id_municipio FROM municipios WHERE nome = 'Rio de Janeiro'), '98.765.432/0001-88', 'Sistema B', 'www.github.com', 'usuario2', 'senha456', 6, 'Segundo registro'),
(3, (SELECT id_unidade FROM unidades WHERE cnpj = '21.987.654/0001-02'), (SELECT id_municipio FROM municipios WHERE nome = 'Belo Horizonte'), '56.789.123/0001-77', 'Sistema C', 'www.github.com/alysonvitalino', 'usuario3', 'senha789', 9, 'Terceiro registro'),
(4, (SELECT id_unidade FROM unidades WHERE cnpj = '34.567.890/0001-03'), (SELECT id_municipio FROM municipios WHERE nome = 'Porto Alegre'), '34.567.890/0001-66', 'Sistema D', 'www.youtube.com', 'usuario4', 'senha101', 12, 'Quarto registro'),
(5, (SELECT id_unidade FROM unidades WHERE cnpj = '45.678.901/0001-04'), (SELECT id_municipio FROM municipios WHERE nome = 'Curitiba'), '78.901.234/0001-55', 'Sistema E', 'www.instagram.com', 'usuario5', 'senha202', 15, 'Quinto registro'),
(6, (SELECT id_unidade FROM unidades WHERE cnpj = '56.789.012/0001-05'), (SELECT id_municipio FROM municipios WHERE nome = 'Salvador'), '45.678.901/0001-44', 'Sistema F', 'www.facebook.com', 'usuario6', 'senha303', 18, 'Sexto registro'),
(7, (SELECT id_unidade FROM unidades WHERE cnpj = '67.890.123/0001-06'), (SELECT id_municipio FROM municipios WHERE nome = 'Fortaleza'), '23.456.789/0001-33', 'Sistema G', 'www.chatgpt.com', 'usuario7', 'senha404', 21, 'Sétimo registro'),
(8, (SELECT id_unidade FROM unidades WHERE cnpj = '78.901.234/0001-07'), (SELECT id_municipio FROM municipios WHERE nome = 'Recife'), '67.890.123/0001-22', 'Sistema H', 'www.gmail.com', 'usuario8', 'senha505', 24, 'Oitavo registro'),
(9, (SELECT id_unidade FROM unidades WHERE cnpj = '89.012.345/0001-08'), (SELECT id_municipio FROM municipios WHERE nome = 'Manaus'), '89.012.345/0001-11', 'Sistema I', 'classroom.google.com', 'usuario9', 'senha606', 27, 'Nono registro'),
(10, (SELECT id_unidade FROM unidades WHERE cnpj = '90.123.456/0001-09'), (SELECT id_municipio FROM municipios WHERE nome = 'Goiânia'), '90.123.456/0001-00', 'Sistema J', 'www.excalidraw.com', 'usuario10', 'senha707', 30, 'Décimo registro');

SELECT cod_entidade, id_unidade FROM unidades;
SELECT * FROM aliquotas;
SELECT * FROM cadastro;
SELECT * FROM municipios;